spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hub.gisdatahub
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

seoul:
  open-api:
    key: ${SEOUL_OPENDATA_KEY:}
    base-url: http://openapi.seoul.go.kr:8088
    living-population-collect-cron: ${SEOUL_LIVING_POPULATION_COLLECT_CRON:0 0 3 * * *}
    sdot-visitor-collect-cron: ${SEOUL_SDOT_VISITOR_COLLECT_CRON:0 20 3 * * *}
    district-living-population-service-name: SPOP_LOCAL_RESD_PPLTN
    air-quality-start: 1
    air-quality-end: 25
    district-living-population-start: 1
    district-living-population-end: 1000

aws:
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
   
